export const pokemonConstants = {
  GET_POKEMON_LIST_REQUEST: "GET_POKEMON_LIST_REQUEST",
  GET_POKEMON_LIST_FAILURE: "GET_POKEMON_LIST_FAILURE",
  GET_POKEMON_LIST_SUCCESS: "GET_POKEMON_LIST_SUCCESS",
};